"""initial_tables

Revision ID: 79e6e24c42ba
Revises: 
Create Date: 2026-03-25 20:35:17.863547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e6e24c42ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('ntfy_topic', sa.String(length=255), nullable=True),
    sa.Column('schedule_cron', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('schwab_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('app_key_enc', sa.String(length=512), nullable=False),
    sa.Column('app_secret_enc', sa.String(length=512), nullable=False),
    sa.Column('refresh_token_enc', sa.String(length=1024), nullable=True),
    sa.Column('rotation_state', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('min_order_value', sa.Float(), nullable=False),
    sa.Column('remainder_symbol', sa.String(length=10), nullable=False),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schwab_accounts_id'), 'schwab_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_schwab_accounts_user_id'), 'schwab_accounts', ['user_id'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('target_pct', sa.Float(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['schwab_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_account_id'), 'allocations', ['account_id'], unique=False)
    op.create_index(op.f('ix_allocations_id'), 'allocations', ['id'], unique=False)
    op.create_table('trade_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('shares', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['schwab_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_logs_account_id'), 'trade_logs', ['account_id'], unique=False)
    op.create_index(op.f('ix_trade_logs_id'), 'trade_logs', ['id'], unique=False)
    op.create_index(op.f('ix_trade_logs_user_id'), 'trade_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_logs_user_id'), table_name='trade_logs')
    op.drop_index(op.f('ix_trade_logs_id'), table_name='trade_logs')
    op.drop_index(op.f('ix_trade_logs_account_id'), table_name='trade_logs')
    op.drop_table('trade_logs')
    op.drop_index(op.f('ix_allocations_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_account_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_schwab_accounts_user_id'), table_name='schwab_accounts')
    op.drop_index(op.f('ix_schwab_accounts_id'), table_name='schwab_accounts')
    op.drop_table('schwab_accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
